### ISSUE TITLE
Persistent Textbox

### ISSUE THREAD

**Issue by orian34** [07th-mod/higurashi-assembly#14]
There's an issue with Tsumi's engine caused by something related to the opening question script(because it only happens if the script fires).
I've tried several things and it seems like the engine is changed(maybe a variable issue) and force draws a textbox every two new scenes(I have no idea why it's so specific, lol), the textbox can't be disabled as if it's baked in the background.

The current version:
https://www.youtube.com/watch?v=SpQTJeiCtng

And after changing one scene draw to offset the order:
https://www.youtube.com/watch?v=0WSx9SBZpIA

I just changed this line:
https://github.com/07th-mod/tsumihoroboshi/blob/d1a6567febc2586dc3624d35ef139b928135a78e/Update/flow.txt#L23

with **DrawScene( "07thlogo", 1000 );**

EDIT by enumag:

To test it you need to delete `global.dat` in your tsumi save directory.

I think there is some sort of a problem with `DisableWindow` [here](https://github.com/07th-mod/tsumihoroboshi/blob/master/Update/%26opening.txt#L29).

**Comment by orian34** [comment]
After some testing, I can give more clues. And it is not related to the intro script in the end.

That bug only happens after the textbox is drawn for the first time.
Just writing some gibberish will cause the bug to happen so whatever is in the engine when drawing the textbox is causing the bug as soon as it's drawn once.

Also, seems like the textbox is really, really baked in.
I can't disable it, I can't fade it out(as if it was a sprite or bustshot), and I can even open a new textbox to write a line of text, then clean it up and disable the new textbox without having the stuck one batting an eye.

**Comment by enumag** [comment]
@idealpersona @tellowkrinkle This is high priority to fix soon. Orian's work with comparing Tsumi to PS3 would be negatively affected with this bug still present. Please look into it.

**Comment by enumag** [comment]
Note: It seems that `HideWindow` also takes one argument (a number) controling the speed of the animation.

**Comment by orian34** [comment]
by "drawn for the first time" I mean that it won't happen no matter what you do as long as there is no textbox involved, but as soon as one is drawn, it'll be persistent until you restart the game.

**Comment by orian34** [comment]
@idealpersona 
HideWindow is just a method to fade out the current textbox, but because the bugged textbox is not considered the current textbox, it doesn't work.

**Comment by idealpersona** [comment]
This is fixed in https://github.com/07th-mod/higurashi-assembly/commit/5b9339ae3b8563857b4024e66c25618306d2061e

I believe it was either an error in the original port of the mod or an error when first setting up the source code branches under this repo.

Basically there was a change between meakashi and tsumi reducing the number of background layers from 2 to 1, and by the power of copy+paste I think I ended up reverting that change because I was replacing a lot of vanilla code with what the mod had from the previous arc.

It's also possible this happened because of a merge and if so there might be a problem with our git workflow but it's probably not that.

**Comment by orian34** [comment]
Awesome, thanks for fixing it!

**Comment by enumag** [comment]
Fixed in https://github.com/07th-mod/tsumihoroboshi/releases/tag/v1.3.0
