### ISSUE TITLE
Reliable way to default ps3 sprites

### ISSUE THREAD

**Issue by idealpersona** [07th-mod/higurashi-assembly#19]
So, while doing a sprite lockdown to PS3 for the console arcs (https://github.com/07th-mod/higurashi-console-arcs/issues/39) I found a reliable way to safely initialize the art style, so per @DoctorDiablo 's suggestion we can actually integrate this into the main arcs.  The issue is that there are separate states in the game code and in the scripts that need to be kept in sync, so setting the art style flag in the scripts never cut it (or might even be dangerous).

EDIT: the below explanation turned out to be slightly wrong, so it is not totally pertinent now.

The game on launch will load global flags from global.dat, or - in the case of a first-time launch - initialize globals with defaults.  In either case, right after doing that, the game syncs in internal state with those flags, including that art style.  So it turns out we can just change the value in this line https://github.com/07th-mod/higurashi-assembly/blob/c4ec6a4db7e8c0a8675b9fe85bb24247bc9f5a61/Assets.Scripts.Core.Buriko/BurikoMemory.cs#L131 from 1 to 0 and PS3 sprites would then be active by default (with lipsync on too).

But the catch comes because this flag - unlike many others that we've added - already exists in the vanilla game.  This mechanism only works if it's the first time the user has installed and they never ran the vanilla game before the mod, which is probably a toss-up.  An alternative would be to insert a hook around here based on some global flag that detects that it's the first time initializing the mod.  We could introduce something new for this, but there's a good chance we can use GMOD_SETTING_LOADER, which determines the first-time initialization in init.txt.  When these variables are initialized, the init script should not yet have executed, so we can branch that off of detecting that flag = 0.  Maybe also worth incorporating that change in the referenced line above for consistency, but it *should* prove redundant.

**Comment by idealpersona** [comment]
Turned out I was wrong about some parts of the flag initialization routine, so I ended up implementing it differently as that pull request shows.  Now it's safe to initialize in init.txt.

But every arc's GMOD_SETTING_LOADER blocks in init.txt will have to be modified with a change like this @enumag - not sure if that's a script compiler change?

![image](https://user-images.githubusercontent.com/36429889/51443731-c7959d80-1caa-11e9-9333-961c7abb41a1.png)

**Comment by enumag** [comment]
Fixed the [compiler](https://github.com/07th-mod/higurashi-patch-compiler/commit/c5cd4a43e13ba0802d00c752d193235d3858192e). All existing chapters need to be updated manually though.

**Comment by idealpersona** [comment]
@enumag I take that to mean compiler does not get run on updates to existing arcs?

**Comment by enumag** [comment]
No, compiler is a one-time thing for each arc.

**Comment by idealpersona** [comment]
ok i'll wait to get feedback on the code changes before doing that.

**Comment by idealpersona** [comment]
Just applied the script changes to all arcs on master.

Code changes must be merged from mod branch into the other arcs **prior to any new releases**.  I'll wait for feedback on that branch and see what other changes we want to include to ease the testing burden.

**Comment by idealpersona** [comment]
Seems to be in the arc branches.  Closing for now, can reopen if significant issues.
