### ISSUE TITLE
Line in new history view not clickable near the top of the screen

### ISSUE THREAD

**Issue by enumag** [07th-mod/higurashi-assembly#23]
I tested the new history view in Tsumi to see if everything works fine and found a little bug. It is impossible to click a line that is at the top of the screen. Not one specific line, simply any that you scroll into that position. When you scroll the line lower it works just fine.

![history](https://user-images.githubusercontent.com/539462/54048082-063ed300-41d9-11e9-861b-a76275ccede3.png)

EDIT: At first I was unable to reproduce this in Onikakushi but now I did so this affects all chapters. It seems that the line at the top isn't non-clickable always, just most of the time. I did encounter cases when it was clickable both in Oni and in Tsumi but it seemed rare and I could not figure out any pattern.

**Comment by tellowkrinkle** [comment]
Alright I think it was being caused by the fact that while I removed the text and voices from labels that stopped being needed (I store enough label objects to possibly have enough for every line being a separate label, then update their positions and text as needed), I never removed their hitboxes so invisible labels would end up covering up the ones we actually wanted to click on.

It should be fixed in f7804b3acbf683eee9c5b2d417a13ac8f956afa2, though you should make sure by trying out one of the builds once they finish.

**Comment by enumag** [comment]
I'll test it when I get home. Thanks!

**Comment by enumag** [comment]
With the fixed DLL I managed to do this:

![hover](https://user-images.githubusercontent.com/539462/54221223-5d071e00-44f3-11e9-9d8f-75f867846180.png)

I'm not entirely sure how though and can't replicate it reliably. Sometimes a line that is only partially visible on the top of the screen turns blue - but if I scroll to get it entirely visible it turns white again. It isn't even always a voiced line, some normal lines turned blue this way too.

**Comment by tellowkrinkle** [comment]
Hopefully 734b0fba517b73b280a65a6097810ed662dc42ed fixes it?

Could you test the latest Onikakushi build once it finishes?

**Comment by enumag** [comment]
Shouldn't you merge the `mod` branch into `oni-mod` first? The DLLs linked in readme are compiled from `<chapter>-mod` branches I believe.

**Comment by tellowkrinkle** [comment]
Oops I forgot to push the merge commit, should be building now

**Comment by enumag** [comment]
It seems to have fixed the previous issue but now a voiced line near the top of the screen is not highlighted in some cases. Particularly it sometime happens when I have the cursor near the top and then use the mousewheel to scroll a line that was lower on the screen to be below the cursor. Clicking the line still works fine.

**Comment by tellowkrinkle** [comment]
Alright see if it works now with 182fd76738e169bd058d894ec3da080ad74b42af

**Comment by enumag** [comment]
I still experienced the issue but it was much less common - I wouldn't have noticed it at all if I didn't focus on it. I think it's good enough to be released. Thank you very much!
