### ISSUE TITLE
Config screen improvements

### ISSUE THREAD

**Issue by enumag** [07th-mod/higurashi-assembly#32]
It bothers me a bit that the voices volume can only be changed by hotkeys and not directly in the game menu. After some discussion with @ItaloKnox this is what we'd like to do:

We should repurpose one of the less needed bars for this. In our case we could drop the "auto mode message speed" and simply use the normal message speed instead in the game.

It would also be nice if we could change the order of the bars like this:

- textbox opacity
- voices volume
- music volume
- sound effects volume
- message speed
- auto mode advance speed

Changing the labels is relatibely easy. We will just change the labels in photoshop and recompile the UIs. The complicated part is to make the DLL work this way.

**Comment by drojf** [comment]
This appears to be implemented already (by the above PR)
