### ISSUE TITLE
Increase the configurable resolutions

### ISSUE THREAD

**Issue by enumag** [07th-mod/higurashi-assembly#37]
The current game resolutions available through the config screen are quite small considering we're using HD graphics. In my opinion we should change the options available there to some bigger sizes. Italo suggested these (I agree):

- 1280x720
- 1920x1080
- 2560x1440

I can change the UI text easily when the DLLs are updated.

**Comment by tellowkrinkle** [comment]
Should I merge this through now or later?

**Comment by enumag** [comment]
@tellowkrinkle yeah, merge it to all chapters please... console arcs too

**Comment by tellowkrinkle** [comment]
Alright should be good once the builds finish

**Comment by enumag** [comment]
Awesome. Thank you!
