### ISSUE TITLE
Transparent sprites

### ISSUE THREAD

**Issue by enumag** [07th-mod/higurashi-assembly#38]
In Meakashi, Minagoroshi and console arcs we need to have partially transparent sprites in some cases. Based on the discussion on Discord it seems the engine has the ability to do that and the commands even have such API but the transparency is not preserved when lipsyncing.

Check the current state to find out which commands provide this and how and make it work with lipsync too.

**Comment by enumag** [comment]
Also let me ping @voodoochiledev. He might want to help too.

**Comment by orian34** [comment]
It would require an efficient way to change the opacity as currently, I believe only the DrawSprite has the ability to do so, and opacity isn't saved for lipsync. 

To have it work properly, we'd need :
1- A way to change opacity for the ModDrawCharacter command, which is compatible with lipsync.
2-Lipsync stores the opacity when changing between sprites to stay consistent while the character talks.

**Comment by tellowkrinkle** [comment]
Should be addressed by 3400a02a60613892962d44c078023c70025a590b
Call `ModSetLayerFilter(layerNumber, alpha, color)` to set the filter that will be applied all future images loaded to the given layer.

`layerNumber` is a layer ID (same as the first number in most drawing calls)

`alpha` is a number 0-256 and acts as a multiplier for alpha (0 is invisible, 256 is opaque)

`color` is a string describing a color filter.  `"none"` or `""` is no filter, and starting with c9a1a6fe24e693d897fcdd1854481781e4a1fafb you can use `"flashback"`, `"sunset"`, and `"night"` for approximate replicas of our current filters, three integers separated by commas for a custom filter where each number multiplies red, green, and blue channels, or nine integers separated by commas for a custom filter where each channel is made with a linear combination of the original color pixel (so `"1,2,3,4,5,6,7,8,9"` would mean "newR = 1/256 r + 2/256 g + 3/256 b; newG = 4/256 r + 5/256 g + 6/256 b; newB = 7/256 r + 8/256 g + 9/256 b")

**Comment by orian34** [comment]
Works pretty great, here's just a couple issues left:
-Alpha doesn't work if you have a filter, so you can't combine them.
-Night and sunset filter doesn't work? It shows as normal. Flashback works.

**Comment by tellowkrinkle** [comment]
I forgot to merge c9a1a6fe24e693d897fcdd1854481781e4a1fafb into the other arcs, should be fixed

Alpha and filter mixing seems to work for me:
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/3315070/63386230-2d90f300-c368-11e9-86e9-be063c238953.png">

**Comment by enumag** [comment]
@tellowkrinkle When you posted the comparisons on Discord I gave you this feedback. Not sure if you read it. Could you try to make some improvements?

**Flashback**: Aside from sprites with anything white it's pretty much the same. Very good approximation, definitely useable. :thumbsup: 
**Night**: Not so close as flashbacks but I wasn't even sure which I liked more so the new ones are acceptable in my opinion. :ok_hand: 
**Sunset**: Unfortunately very different and I like the old sprites a lot more. Could you try to get closer to the originals? :thumbsdown:

**Comment by enumag** [comment]
Ah forgot to close this one. The latest implementation seems ok.
