### ISSUE TITLE
Compilation progress indicator

### ISSUE THREAD

**Issue by enumag** [07th-mod/higurashi-assembly#39]
The vanilla version of Minagoroshi comes with a nice new feature of showing the scripts compilation progress on startup instead od just a blackscreen like the previous chapters.

Try to backport that into the previous chapters.

@idealpersona @tellowkrinkle @voodoochiledev

**Comment by idealpersona** [comment]
I'm getting a lot of these exceptions when firing up the game and i also got some in between each script compile when running the game for the first time, so i'm thinking this is related. Not sure if it amounts to any significant issue or just log noise but noting here for future reference.

```
NullReferenceException: Object reference not set to an instance of an object
  at Assets.Scripts.UI.MainUIController.OnGUI () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

NullReferenceException: Object reference not set to an instance of an object
  at Assets.Scripts.UI.MainUIController.OnGUI () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

NullReferenceException: Object reference not set to an instance of an object
  at Assets.Scripts.UI.MainUIController.OnGUI () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

NullReferenceException: Object reference not set to an instance of an object
  at Assets.Scripts.UI.MainUIController.OnGUI () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

NullReferenceException: Object reference not set to an instance of an object
  at Assets.Scripts.UI.MainUIController.OnGUI () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

NullReferenceException: Object reference not set to an instance of an object
  at Assets.Scripts.UI.MainUIController.OnGUI () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)
```

**Comment by tellowkrinkle** [comment]
Is this in a backport attempt?

**Comment by idealpersona** [comment]
nah this is on mina

**Comment by drojf** [comment]
I've backported the compilation indicator to chapters 1-6, should now be live on all those chapters.

I've just used the "Toaster" (the little mod notification that appears at the top of the screen), because on previous chapters the text object on the bottom right hand corner doesn't exist.

See here for more details: https://github.com/07th-mod/higurashi-assembly/pull/88
