### ISSUE TITLE
Different positionning for choice selection

### ISSUE THREAD

**Issue by orian34** [07th-mod/higurashi-assembly#42]
There are discrepancies between arcs causing an offset for the choice selection. 
Here are samples:
- Oni
![onichoice](https://user-images.githubusercontent.com/12663654/63349219-3e873780-c35b-11e9-8f61-c2f1f7eb8b32.png)
- Hima
![himachoice](https://user-images.githubusercontent.com/12663654/63349279-5b236f80-c35b-11e9-90f9-ad2918b8a2fc.png)
- Mina
![minachoice](https://user-images.githubusercontent.com/12663654/63349287-62e31400-c35b-11e9-9b62-26acc0a2b6a3.png)

Goal is to uniformize them

**Comment by DoctorDiablo** [comment]
For reference, here's how it looks in the console arcs.
![ConsoleArcsChoice](https://user-images.githubusercontent.com/20390474/63440287-924a5d00-c3fd-11e9-9603-5a047f2dd5d0.png)

The Select() function is also used to implement the scenario selection screen in the console arcs, so it has some special logic in there to switch to a two column layout if there are more than 8 options.  That functionality will probably never be used anywhere else, but if you want everything to be  completely standardized you could consider porting that too.

**Comment by enumag** [comment]
@idealpersona can you take a look at this pls?

**Comment by tellowkrinkle** [comment]
I tried just copying the console arcs code over, see how these work (I don't expect the Onikakushi one to have its font fixed, but the positioning might work better)
[ACSOnikakushi.zip](https://github.com/07th-mod/higurashi-assembly/files/3649618/ACSOnikakushi.zip)
[ACSHimatsubushi.zip](https://github.com/07th-mod/higurashi-assembly/files/3649616/ACSHimatsubushi.zip)
[ACSMinagoroshi.zip](https://github.com/07th-mod/higurashi-assembly/files/3649617/ACSMinagoroshi.zip)

**Comment by enumag** [comment]
Orian tested it and said it was fixed now. Can you merge the changes pls?

**Comment by tellowkrinkle** [comment]
Pre-hima text should be the right size as of e358cae79ef3c7c15c7091bb69efd82764745649
