### ISSUE TITLE
Textbox forced opacity bug

### ISSUE THREAD

**Issue by orian34** [07th-mod/higurashi-assembly#43]
I think that was a bug we fixed at some point, but it's back apparently.
Textbox opacity is forcefully synced to message speed in settings, which means changing message speed will change textbox opacity as well. 
Changing the opacity setting doesn't work since it's the message speed that matters.

**Comment by enumag** [comment]
Perhaps this was somehow caused by https://github.com/07th-mod/higurashi-assembly/pull/34? But the code seems correct. Someone please double-check this with updated DLL and UI.

**Comment by orian34** [comment]
was fixed ye
