### ISSUE TITLE
Bug with sprites aspect ratio

### ISSUE THREAD

**Issue by enumag** [07th-mod/higurashi-assembly#47]
Switching between art styles doesn't work well because the sprites have different aspect ratio.

For instance if I start the game with ryukishi sprites like this:

![image](https://user-images.githubusercontent.com/539462/68894440-9c8fa500-0727-11ea-9ee2-013753c814c4.png)

and then switch to PS3 sprites it turns out like this:

![image](https://user-images.githubusercontent.com/539462/68894471-a5807680-0727-11ea-86a5-715aa3d2e361.png)

Similarily if I start with PS3 sprites then OG sprites are way too large.

**Comment by tellowkrinkle** [comment]
Should be fixed by cee4e033c5287ccd9decf31119be361118d55170
