### ISSUE TITLE
`switchsound` folder is not included in main chapters, and audio files are very quiet

### ISSUE THREAD

**Issue by drojf** [07th-mod/higurashi-assembly#50]
I noticed the mod dll references SE files in the `switchsound` folder, which is included only in the Console arcs version of our mod: 

- 0.ogg 
- 1.ogg
- 2.ogg
- 3.ogg
- 4.ogg
- 5.ogg
- enable.ogg, 
- disable.ogg

These files are not included in the other versions of the game, so these SE never play.

I then included the files, but they are too quiet.

Foobar's replaygain burn in feature could be used to fix the files (or any other program which can normalize the levels)

Todo:

- [x] normalize the levels of the files in the `switchsound` folder. I don't think they should be normalized to 0db, perhaps -6dB
- [ ] include the `switchsound` folder in all our releases
- [x] include a sample voice file so you can test the voice playback level when voice volume is adjusted. Perhaps `StreamingAssets\voice\voice_test.ogg` 
- [ ] optional: include a fallback so if the files are missing, it just plays the default click sound. but I guess if the sound doesn't play it's no big deal.

**Comment by ItaloKnox** [comment]
> Foobar's replaygain burn in feature could be used to fix the files (or any other program which can normalize the levels)

I think replaygain does not work with the engine. I tried it once and it didn't do anything. If you post a zip with the sounds I can try to do something about it.

**Comment by drojf** [comment]
Foobar has this feature:

![image](https://user-images.githubusercontent.com/1249449/97083686-8ee3de80-165d-11eb-87c2-a6ee02106b76.png)

which allows you to burn in the replaygain volume change during conversion (as in it applies the gain to the audio data, rather than just copying the replaygain metadata).

After doing this conversion the result is this:

[switchsound_and_voice_test.zip](https://github.com/07th-mod/higurashi-assembly/files/5432987/switchsound_and_voice_test.zip) (the voice_test.ogg is **not** normalized on purpose - it should have the same levels as the rest of the voice files)

I don't have the source file to work with, so you'll lose some quality with this re-encode, but I don't think you could tell the difference. If someone has the source files and feel free to re-encode it.

**Comment by ItaloKnox** [comment]
Wait, is that zip the one with the replaygain added or the files before the application? Doing it after applying replaygain directly to the file (which should be a transcode of a transcode), will degrade it quite a lot by introducing distortion. If I get the files with no replaygain applied, I can normalize them in -14db integrated (aka Spotify levels).

**Comment by drojf** [comment]
Here are the original ogg files from our console arcs patch, plus that one voice file [switchsound_and_voice_test_original_ogg.zip](https://github.com/07th-mod/higurashi-assembly/files/5434040/switchsound_and_voice_test_original_ogg.zip)

Now that I think about it, the original switch game's file format was some variant of .ogg, so these files might not even have been converted before (my previous comment implied that there was a lossy (original game format -> .ogg) conversion, but I think the (original game format -> .ogg) conversion might have been lossless, since the original game format was some variant of .ogg))

**Comment by drojf** [comment]
We now include the audio files in the extra "og-dll-asset-update" archive (like https://07th-mod.com/rikachama/og-dll-asset-update/matsuribayashi-og-dll-asset-update.7z)
