### ISSUE TITLE
Missing LArc flag

### ISSUE THREAD

**Issue by enumag** [07th-mod/higurashi-assembly#8]
The flag was removed in https://github.com/07th-mod/higurashi-assembly/commit/9fece2032622625011f8a87185b264a0a716d55a but is still used [here](https://github.com/07th-mod/higurashi-assembly/blob/mod/MOD.Scripts.UI.Tips/MODTipsController.cs) causing this error:

```
Exception: Unable to get flag with the name LArc, flag not found.
  at Assets.Scripts.Core.Buriko.BurikoMemory.GetFlag (System.String flagname) [0x00000] in <filename unknown>:0 

  at MOD.Scripts.UI.Tips.MODTipsController.get_Tips () [0x00000] in <filename unknown>:0 

  at Assets.Scripts.UI.Extra.ExtraButton.Awake () [0x00000] in <filename unknown>:0 
UnityEngine.Object:Internal_CloneSingle(Object)
UnityEngine.Object:Instantiate(GameObject)
Assets.Scripts.Core.State.StateExtraScreen:.ctor()
Assets.Scripts.Core.Buriko.BurikoScriptFile:OperationViewExtras()
Assets.Scripts.Core.Buriko.BurikoScriptFile:ExecuteOperation(BurikoOperations)
Assets.Scripts.Core.Buriko.BurikoScriptFile:CommandOperation()
Assets.Scripts.Core.Buriko.BurikoScriptFile:Next()
Assets.Scripts.Core.Buriko.BurikoScriptSystem:Advance()
Assets.Scripts.Core.GameSystem:Update()
 
```

**Comment by enumag** [comment]
@tellowkrinkle You commited it only to console arcs but I found the bug in Oni. Shouldn't it be changed in the `mod` branch?

**Comment by tellowkrinkle** [comment]
Ahh at the moment none of the non console arcs builds have `LConsoleArc` or `LArc`.  Should I add it to them?

**Comment by enumag** [comment]
@tellowkrinkle I don't know what the flag is for. It sounds specific for the console arcs in which case I guess we need to remove the usage in MODTipsController.cs?

**Comment by tellowkrinkle** [comment]
Alright it looks like the flag is used to select which tips are shown.  It reads the flag and chooses the dictionary with that key in the JSON.  How do we want to deal with it in other arcs?  Always use key 0?

**Comment by enumag** [comment]
Yeah, I think so.

By the way, as I said in the other issue, keys in json should not be integers. Can you make it work with string keys too? As in `"0": []`? Maybe it already does, I'm not sure.

**Comment by tellowkrinkle** [comment]
Could you try changing the console arcs's integer keys to string keys and see if it breaks?

**Comment by enumag** [comment]
Sure, give me a minute.

**Comment by enumag** [comment]
Hmm looks like I can't. I didn't play the console arcs yet so the extra menu is locked for me. I'm not sure what flag I need to set to unlock it.

**Comment by tellowkrinkle** [comment]
Ahh that's the issue I have too, let me go look up flags

**Comment by tellowkrinkle** [comment]
[Onikakushi Assembly-CSharp.dll.zip](https://github.com/07th-mod/higurashi-assembly/files/2497997/Onikakushi.Assembly-CSharp.dll.zip)
I only pushed to mod so we won't get the CI build out, see if this works (both with and without int keys)

**Comment by enumag** [comment]
Works fine. Thank you!
