### ISSUE TITLE
Can't retrieve the result value of Select

### ISSUE THREAD

**Issue by enumag** [07th-mod/higurashi-assembly#9]
In Hima and newer chapters the value is retrieved with `LoadValueFromLocalWork(SelectResult)`, for example [here](https://github.com/07th-mod/higurashi-console-arcs/blob/master/Update/chapterselect.txt#L59).

In Oni it causes this error in the log:

```
Exception: &opening.mg (5): ReadVariable: Operation LoadValueFromLocalWork Parameter 1 could not be read. Generated exception: System.Exception: Unable to get flag with the name SelectResult, flag not found.
```

It seems you need to add a flag called SelectResult or something. Also make sure the Select value is actually stored there.

**Comment by tellowkrinkle** [comment]
Fixed by c5cbcbbdb543acc19cebb86c542b1a07562e1f4d
